resources:
  repositories:
    - repository: common
      type: github
      name: sbezhuk/beebase-common
      ref: refs/tags/v0.3.0
      endpoint: github-sbezhuk # GitHub service connection - see deployment report

extends:
  template: ci/azure-pipelines-service-template.yml@common
  parameters:
    serviceName: beebase-statistics-service
    hasMigrations: false
